version: '2'
services:
    eleicoes-app:
        image: eleicoes
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://eleicoes-postgresql:5432/eleicoes
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    eleicoes-postgresql:
        extends:
            file: postgresql.yml
            service: eleicoes-postgresql
